---

- name: Fetch plugins from remote site
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
  with_items:
    - "{{ grafana_plugins }}"
  retries: 5
  delay: 5

- name: Install required plugins
  unarchive:
    src: "/tmp/{{ item.name }}"
    dest: "{{ grafana_plugins_dir }}"
    creates: "{{ grafana_plugins_dir }}/{{ item.name }}"
    owner: grafana
    group: grafana
    copy: no
  notify:
    - restart grafana-server
  with_items:
    - "{{ grafana_plugins }}"


# install https://github.com/openstack/monasca-grafana-datasource
# https://github.com/grafana/grafana/pull/3963
